Some weights of the model checkpoint at microsoft/deberta-v3-large were not used when initializing DebertaV2Model: ['lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'mask_predictions.dense.weight', 'mask_predictions.classifier.bias', 'mask_predictions.LayerNorm.bias', 'lm_predictions.lm_head.LayerNorm.bias', 'lm_predictions.lm_head.dense.weight', 'mask_predictions.LayerNorm.weight', 'mask_predictions.classifier.weight', 'lm_predictions.lm_head.bias', 'mask_predictions.dense.bias']
- This IS expected if you are initializing DebertaV2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaV2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/Users/qcqced/Desktop/SAMSUNG/venv/lib/python3.9/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Traceback (most recent call last):
  File "/Users/qcqced/Desktop/GitHub/FeedBackPrize_3/train.py", line 39, in <module>
    main('fbp3_config.json', CFG)
  File "/Users/qcqced/Desktop/GitHub/FeedBackPrize_3/train.py", line 20, in main
    train_loop(cfg)
  File "/Users/qcqced/Desktop/GitHub/FeedBackPrize_3/trainer/train_loop.py", line 34, in train_loop
    lr_scheduler, swa_scheduler, awp, save_parameter = train_input.model_setting(len(train))
  File "/Users/qcqced/Desktop/GitHub/FeedBackPrize_3/trainer/trainer.py", line 69, in model_setting
    optimizer = getattr(transformers, self.cfg.optimizer)(
  File "/Users/qcqced/Desktop/SAMSUNG/venv/lib/python3.9/site-packages/transformers/optimization.py", line 322, in __init__
    super().__init__(params, defaults)
  File "/Users/qcqced/Desktop/SAMSUNG/venv/lib/python3.9/site-packages/torch/optim/optimizer.py", line 192, in __init__
    self.add_param_group(param_group)
  File "/Users/qcqced/Desktop/SAMSUNG/venv/lib/python3.9/site-packages/torch/optim/optimizer.py", line 535, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group